package net.runelite.client.live.inDevelopment.biggs.Executioner;

public enum State {
    BREAKING,
    GOING_TO_BANK, OPEN_BANK, DEPOSIT, WITHDRAW, EQUIP,
    TIMEOUT, IDLE, ANIMATE, CHECK_RESTOCK,
    TRAVERSE, TELE_TO_AREA, SKIP_TASK,
    GO_NULODION, RETRIEVE_CANNON, RETURN_EDGE,
    HOP_DITCH, GO_DITCH, ATTACKING,
    GO_SLAYER_MASTER, GETTING_TASK,
    LOOTING, RETURNING, HEAL, ENERGY,
}
