package net.runelite.client.live.inDevelopment.biggs.Executioner.MichaelJackson;

import lombok.Getter;
import net.runelite.api.coords.WorldArea;
import net.runelite.api.coords.WorldPoint;



@Getter
public enum MonsterRules {
    ABYSSAL_DEMONS( //DONE
            "Abyssal demon",
            "Kristilia",
            null,
            new WorldArea(3328, 10143, 25, 32, 0),
            null,
            new WorldPoint(3032, 3702, 0),
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint(3333,10161, 0),
            new WorldPoint(3341,10160, 0)
    ),
    ANKOU( //DONE
            "Ankou",
            "Kristilia",
            null,
            new WorldArea(3336, 10068, 52, 27, 0),
            null,
            null,
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint(3361,10077, 0),
            new WorldPoint(3357,10079, 0)
    ),
    AVIANSIE( //SKIP FOR NOW
            "Aviansie",
            "Kristilia",
            null,
            new WorldArea(3015, 10142, 29, 25, 0),
            new WorldPoint(3026, 10158, 0),
            null,
            null,
            "Burning amulet(",
            true,
            false,
            null,
            null,
            null
    ),
    BANDITS( //DONE
            "Bandit", //DONE
            "Kristilia",
            null,
            new WorldArea(3022, 3696, 30, 14, 0),
            new WorldPoint(3033, 3699, 0),
            null,
            null,
            "Burning amulet(",
            true,
            false,
            new WorldArea(3019, 3646, 36, 50, 0),
            null,
            null
    ),
    BEARS( //DONE
            "Grizzly bear",
            "Kristilia",
            null,
            new WorldArea(3060, 3587, 41, 46, 0),
            new WorldPoint(3080, 3605,  0),
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null
    ),
    BLACK_DEMONS( //DONE
            "Black demon",
            "Kristilia",
            null,
            new WorldArea(3355, 10111, 31, 17, 0),
            null,
            null,
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint(3367,10112, 0),
            new WorldPoint(3365,10117, 0)
    ),
    BLACK_DRAGONS( //DONE
            "Black dragon",
            "Kristilia",
            null,
            new WorldArea(3352, 10134, 30, 32, 0),
            null,
            null,
            null,
            "Burning amulet(",
            true,
            false,
            null,
            new WorldPoint(3369,10155, 0),
            new WorldPoint(3363,10157, 0)
    ),
    BLACK_KNIGHTS(
            "Black knight",
            "Kristilia",
            null,
            new WorldArea(3020, 3821, 47, 53, 0),
            new WorldPoint(3024, 3850, 0),
            null,
            new WorldPoint(2959, 3668, 0),
            "Burning amulet(",
            true,
            false,
            null,
            null,
            null
    ),
    BLOODVELD( // SKIP FOR NOW
            "Bloodveld",
            "Kristilia",
            null,
            new WorldArea(3022, 10129, 39, 24, 0),
            new WorldPoint(3042, 10145, 0),
            null,
            null,
            "Burning amulet(",
            true,
            false,
            null,
            null,
            null
    ),
    CHAOS_DRUIDS(// SKIP FOR NOW!
            "Chaos druid",
            "Kristilia",
            null,
            new WorldArea(3103, 9922, 27, 22, 0),
            new WorldPoint(3110, 9930, 0),
            null,
            null,
            null,
            false,
            true,
            null,
            null,
            null
    ),
    DARK_WARRIORS( //SKIPTASK
            "Dark warrior",
            "Kristilia",
            null,
            new WorldArea(3025, 3628, 9, 8, 0),
            new WorldPoint(3021, 3632, 0),
            new WorldPoint(3022, 3632, 0),
            new WorldPoint(3021, 3632, 0),
            null,
            false,
            true,
            new WorldArea(3011, 3620, 14, 23, 0),
            null,
            null
    ),
    DUST_DEVILS( //DONE
            "Dust devil",
            "Kristilia",
            null,
            new WorldArea(3418, 10114, 36, 19, 0),
            new WorldPoint(1611, 3611, 0),
            new WorldPoint(1612, 3612, 0),
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint(3449,10123, 0),
            new WorldPoint(3439,10121, 0)
    ),
    EARTH_WARRIORS( //SKIPTASK FOR NOW
            "Earth warrior",
            "Kristilia",
            null,
            new WorldArea(3112, 9982, 18, 22, 0),
            new WorldPoint(3124, 9991, 0),
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null
    ),
    ENTS(
            "Ent",
            "Kristilia",
            null,
            new WorldArea(3209, 3646, 45, 66, 0),
            new WorldPoint(3214, 3686, 0),
            null,
            null,
            "Games necklace(",
            true,
            false,
            null,
            null,
            new WorldPoint(3211, 3686, 0)
    ),
    FIRE_GIANTS( //SKIP SORRY BUD
            "Fire giant",
            "Kristilia",
            null,
            new WorldArea(1614, 3614, 5, 5, 0),
            new WorldPoint(1614, 3614, 0),
            new WorldPoint(1615, 3615, 0),
            null,
            null,
            true,
            true,
            null,
            null,
            null
    ),
    GREATER_DEMONS( //DONE
            "Greater demon",
            "Kristilia",
            null,
            new WorldArea(3414, 10137, 26, 28, 0),
            null,
            null,
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint(3432,10140, 0),
            new WorldPoint(3432,10145, 0)
    ),
    GREEN_DRAGONS( //DONE
            "Green dragon",
            "Kristilia",
            null,
            new WorldArea(3393, 10117, 17, 22, 0),
            null,
            null,
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint (3407, 10121, 0),
            new WorldPoint(3405,10122, 0)
    ),
    HELLHOUNDS( //DONE
            "Hellhound",
            "Kristilia",
            null,
            new WorldArea(3424, 10054, 29, 48, 0),
            null,
            null,
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint(3449,10071, 0),
            new WorldPoint(3443,10081, 0)
    ),
    HILL_GIANTS(
            "Hill giant",
            "Kristilia",
            null,
            new WorldArea(3286, 3632, 52, 70, 0),
            new WorldPoint(3305, 3659, 0),
            new WorldPoint(3160, 3520, 0),
            null,
            null,
            false,
            false,
            null,
            null,
            null
    ),
    ICE_GIANTS( //DONE
            "Ice giant",
            "Kristilia",
            null,
            new WorldArea(3328, 10049, 29, 19, 0),
            null,
            null,
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint(3334,10057, 0),
            new WorldPoint(3340,10057, 0)
    ),
    ICE_WARRIORS(
            "Ice warrior",
            "Kristilia",
            null,
            new WorldArea(2944, 3845, 25, 59, 0),
            new WorldPoint(2952, 3886, 0),
            null,
            new WorldPoint(2959, 3668, 0),
            "Burning amulet(",
            true,
            false,
            null,
            null,
            null
    ),
    JELLIES( //DONE
            "Jelly",
            "Kristilia",
            null,
            new WorldArea(3419, 10095, 21, 19, 0),
            new WorldPoint(1621, 3621, 0),
            new WorldPoint(1622, 3622, 0),
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint(3433,10101, 0),
            new WorldPoint(3429,10103, 0)
    ),
    LAVA_DRAGONS(
            "Lava dragon",
            "Kristilia",
            null,
            null,
            null,
            null,
            null,
            null,
            false,
            true,
            null,
            null,
            null
    ),
    LESSER_DEMONS( //DONE
            "Lesser demon",
            "Kristilia",
            null,
            new WorldArea(3324, 10118, 30, 32, 0),
            null,
            null,
            null,
            "Games necklace(",
            true,
            false,
            null,
            new WorldPoint(3334,10124, 0),
            new WorldPoint(3336,10131, 0)
    ),
    MAGIC_AXES( //SKIPTASK EW LOL
            "Magic axe",
            "Kristilia",
            null,
            new WorldArea(1624, 3624, 5, 5, 0),
            new WorldPoint(1624, 3624, 0),
            null,
            null,
            null,
            true,
            true,
            null,
            null,
            null
    ),
    MAMMOTHS(
            "Mammoth",
            "Kristilia",
            null,
            new WorldArea(3131, 3562, 69, 54, 0),
            new WorldPoint(3162, 3600, 0),
            new WorldPoint(3160, 3520, 0),
            null,
            null,
            false,
            false,
            null,
            null,
            null
    ),
    MOSS_GIANTS(
            "Moss giant",
            "Kristilia",
            null,
            new WorldArea(3121, 3803, 40, 43, 0),
            new WorldPoint(3144, 3829, 0),
            null,
            new WorldPoint(3136, 3737, 0),
            "Revenant cave teleport",
            true,
            false,
            null,
            null,
            null
    ),
    PIRATES( //SKIPTASK (FOR NOW)
            "Pirate",
            "Kristilia",
            null,
            new WorldArea(1620, 3620, 5, 5, 0),
            new WorldPoint(1620, 3620, 0),
            new WorldPoint(1621, 3621, 0),
            null,
            null,
            true,
            true,
            null,
            null,
            null
    ),
    REVENANTS(
            "Revenant goblin",
            "Kristilia",
            null,
            new WorldArea(3186, 10062, 84, 64, 0),
            null,
            null,
            new WorldPoint(3202, 10063, 0),
            "Burning amulet(",
            true,
            false,
            null,
            null,
            null
    ),
    ROGUES( //SKIPTASK
            "Rogue",
            "Kristilia",
            null,
            new WorldArea(1622, 3622, 5, 5, 0),
            new WorldPoint(1622, 3622, 0),
            new WorldPoint(1623, 3623, 0),
            null,
            null,
            false,
            true,
            null,
            null,
            null
    ),
    SCORPIONS(
            "Scorpion", //DONE
            "Kristilia",
            null,
            new WorldArea(3016, 3544, 83, 51, 0),
            new WorldPoint(3051, 3569, 0),
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null
    ),
    SKELETONS( //DONE
            "Skeleton",
            "Kristilia",
            null,
            new WorldArea(3095, 3555, 34, 24, 0),
            new WorldPoint(3101, 3568, 0),
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            new WorldPoint(3104, 3567, 0)
    ),
    SPIDERS( //DONE
            "Deadly red spider",
            "Kristilia",
            null,
            new WorldArea(3115, 9947, 16, 14, 0),
            new WorldPoint(3127, 9955, 0),
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null
    ),
    SPIRITUAL_CREATURES(
            "Spiritual warrior",
            "Kristilia",
            null,
            new WorldArea(3016, 10125, 50, 35, 0),
            new WorldPoint(3036, 10142, 0),
            null,
            null,
            "Burning amulet(",
            true,
            false,
            null,
            null,
            null
    ),
    ZOMBIES( //DONE
            "Zombie",
            "Kristilia",
            null,
            new WorldArea(3150, 3661, 31, 27, 0),
            new WorldPoint(3161, 3674, 0),
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null
    ),
    NECHRYAELS( //DONE
            "Greater Nechryael",
            "Kristilia",
            null,
            new WorldArea(3326, 10096, 17, 22, 0),
            new WorldPoint(1627, 3627, 0),
            null,
            null,
            "Games necklace(",
            false,
            false,
            null,
            new WorldPoint(3334,10100, 0),
            new WorldPoint(3335,10106, 0)

    ),
    //KRISTILLIA FINISH
    /** TURAEL BELOW **/
    BANSHEES(
    "Banshee",
            "Turael",
            null,
            new WorldArea(3442, 3546, 20, 20, 0),
    null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3446, 3552, 0),
    new WorldPoint(3440, 3550, 0)
),
    BATS(
    "Bat",
            "Turael",
            null,
            new WorldArea(3222, 3425, 15, 15, 0),
    null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3227, 3430, 0),
    new WorldPoint(3220, 3432, 0)
),
    BEARS_TURAEL(
    "Black bear",
            "Turael",
            null,
            new WorldArea(2959, 3437, 32, 77, 0),
            new WorldPoint(2973,3490, 0),
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3290, 3400, 0),
    new WorldPoint(3280, 3390, 0)
),
    BIRDS(
            "Bird",
            "Turael",
            null,
            new WorldArea(2610, 3300, 20, 20, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(2615, 3305, 0),
            new WorldPoint(2612, 3297, 0)
    ),
    CAVE_BUGS(
            "Cave bug",
            "Turael",
            null,
            new WorldArea(3120, 9570, 15, 15, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3125, 9575, 0),
            new WorldPoint(3122, 9567, 0)
    ),
    CAVE_CRAWLERS(
            "Cave crawler",
            "Turael",
            null,
            new WorldArea(2790, 9994, 25, 25, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(2795, 9999, 0),
            new WorldPoint(2785, 9989, 0)
    ),
    CAVE_SLIME(
            "Cave slime",
            "Turael",
            null,
            new WorldArea(3210, 9590, 10, 10, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3215, 9595, 0),
            new WorldPoint(3205, 9585, 0)
    ),
    COWS(
            "Cow",
            "Turael",
            null,
            new WorldArea(3250, 3250, 15, 15, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3255, 3255, 0),
            new WorldPoint(3245, 3245, 0)
    ),
    CRAWLING_HANDS(
            "Crawling hand",
            "Turael",
            null,
            new WorldArea(3405, 3575, 30, 30, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3410, 3580, 0),
            new WorldPoint(3400, 3570, 0)
    ),
    DOGS(
            "Dog",
            "Turael",
            null,
            new WorldArea(2860, 2975, 20, 20, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(2865, 2980, 0),
            new WorldPoint(2855, 2970, 0)
    ),
    DWARVES(
            "Dwarf",
            "Turael",
            null,
            new WorldArea(3010, 3450, 25, 25, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3015, 3455, 0),
            new WorldPoint(3005, 3445, 0)
    ),
    GHOSTS(
            "Ghost",
            "Turael",
            null,
            new WorldArea(3230, 3190, 10, 10, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3235, 3195, 0),
            new WorldPoint(3225, 3185, 0)
    ),
    GOBLINS(
            "Goblin",
            "Turael",
            null,
            new WorldArea(3160, 3240, 20, 20, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3165, 3245, 0),
            new WorldPoint(3155, 3235, 0)
    ),
    ICEFIENDS(
            "Icefiend",
            "Turael",
            null,
            new WorldArea(3000, 3475, 15, 15, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3005, 3480, 0),
            new WorldPoint(2995, 3470, 0)
    ),
    KALPHITE(
            "Kalphite Worker",
            "Turael",
            null,
            new WorldArea(3225, 3100, 25, 25, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3230, 3105, 0),
            new WorldPoint(3220, 3095, 0)
    ),
    LIZARDS(
            "Lizard",
            "Turael",
            null,
            new WorldArea(3420, 3040, 20, 20, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3425, 3045, 0),
            new WorldPoint(3415, 3035, 0)
    ),
    MINOTAURS(
            "Minotaur",
            "Turael",
            null,
            new WorldArea(1880, 5240, 15, 15, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(1885, 5245, 0),
            new WorldPoint(1875, 5235, 0)
    ),
    MONKEYS(
            "Monkey",
            "Turael",
            null,
            new WorldArea(2800, 2700, 10, 10, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(2805, 2705, 0),
            new WorldPoint(2795, 2695, 0)
    ),
    RATS(
            "Rat",
            "Turael",
            null,
            new WorldArea(3240, 3210, 5, 5, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3242, 3212, 0),
            new WorldPoint(3238, 3208, 0)
    ),
    SCORPIONS_TURAEL(
            "Scorpion",
            "Turael",
            null,
            new WorldArea(3230, 3150, 15, 15, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3235, 3155, 0),
            new WorldPoint(3225, 3145, 0)
    ),
    SPIDERS_TURAEL(
            "Spider",
            "Turael",
            null,
            new WorldArea(3160, 9580, 10, 10, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3165, 9585, 0),
            new WorldPoint(3155, 9575, 0)
    ),
    WOLVES(
            "Wolf",
            "Turael",
            null,
            new WorldArea(2890, 3675, 25, 25, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(2895, 3680, 0),
            new WorldPoint(2885, 3670, 0)
    ),
    ZOMBIES_TURAEL(
            "Zombie",
            "Turael",
            null,
            new WorldArea(3140, 9650, 20, 20, 0),
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            new WorldPoint(3145, 9655, 0),
            new WorldPoint(3135, 9645, 0)
    );



    private final String npcName;
    private final String slayerMasterName;
    private final int[] requiredSlayerItems; // Can be null
    private final WorldArea npcWorldArea;
    private final WorldPoint outsideWorldPoint;  // Optional
    private final WorldPoint insideWorldPoint;   // Optional
    private final WorldPoint obstacleWorldPoint; // Optional
    @Getter
    private final String traversalItemName; // New field for the item name
    private final boolean useTraversalItem;
    private final boolean skipTask;
    @Getter
    private final WorldArea teleDestinationArea;
    private final WorldPoint insideCavePoint;
    private final WorldPoint cannonPoint;

    MonsterRules(String npcName, String slayerMasterName, int[] requiredSlayerItems, WorldArea npcWorldArea,
                 WorldPoint outsideWorldPoint, WorldPoint insideWorldPoint, WorldPoint obstacleWorldPoint,
                 String traversalItemName, boolean useTraversalItem, boolean skipTask, WorldArea teleDestinationArea, WorldPoint insideCavePoint, WorldPoint cannonPoint) {
        this.npcName = npcName;
        this.slayerMasterName = slayerMasterName;
        this.requiredSlayerItems = requiredSlayerItems;
        this.npcWorldArea = npcWorldArea;
        this.teleDestinationArea = teleDestinationArea;
        this.outsideWorldPoint = outsideWorldPoint;
        this.insideWorldPoint = insideWorldPoint;
        this.obstacleWorldPoint = obstacleWorldPoint;
        this.traversalItemName = traversalItemName;
        this.useTraversalItem = useTraversalItem;
        this.skipTask = skipTask;
        this.insideCavePoint = insideCavePoint;
        this.cannonPoint = cannonPoint;

    }
}
